name: excel
description: A flutter and dart library for reading, creating, editing and updating excel sheets with compatible both on client and server side.
version: 1.1.6
homepage: https://github.com/justkawal/excel

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  archive: ^3.0.0
  xml: ^5.3.1
  equatable: ^2.0.0

dev_dependencies:
  test: ^1.15.7
