name: excel
description: A flutter and dart library for reading, creating, editing and updating excel sheets with compatible both on client and server side.
version: 1.1.5
homepage: https://github.com/justkawal/excel

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  archive: ^2.0.0
  xml: ^4.1.0
  universal_platform: ^0.1.3

dev_dependencies:
  test: ^1.15.7
