name: excel
description: A flutter and dart library for reading, creating, editing and updating excel sheets with compatible both on client and server side.
version: 2.0.0
homepage: https://github.com/justkawal/excel

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  archive: ">=3.1.0 < 4.0.0"
  xml: ">=5.0.0 <7.0.0"
  equatable: ^2.0.5

dev_dependencies:
  test: ^1.21.4
